import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { all, run, exec_raw, transaction, connect } from './index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = path.join(here, 'migrations');

export async function migrate({ silent = false } = {}) {
  const log = (...a) => !silent && console.log(...a);

  await connect();
  await exec_raw(`
    CREATE TABLE IF NOT EXISTS _migrations (
      id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name       TEXT NOT NULL UNIQUE,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  const applied = new Set((await all('SELECT name FROM _migrations')).map((r) => r.name));
  const files = fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql'))
    .sort();

  let count = 0;
  for (const file of files) {
    if (applied.has(file)) continue;
    const sql = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf8');

    // Cada migration roda atomicamente: ou aplica inteira, ou nada.
    try {
      await transaction(async () => {
        await exec_raw(sql);
        await run('INSERT INTO _migrations (name) VALUES (?)', [file]);
      });
      log(`  aplicada: ${file}`);
      count++;
    } catch (err) {
      throw new Error(`Falha na migration ${file}: ${err.message}`);
    }
  }

  log(count === 0 ? '  banco já atualizado' : `  ${count} migration(s) aplicada(s)`);
  return count;
}

// Execução direta: `npm run migrate`.
// `pathToFileURL` é o único jeito confiável de comparar no Windows: o caminho
// tem letra de unidade, barras invertidas e espaços que viram %20 na URL.
const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  console.log('Migrando banco de dados...');
  await migrate();
  console.log('Concluído.');
  process.exit(0);
}
